#!/usr/bin/env bash
#
# fold-capture.sh
#
# Takes a capture directory produced by capture-kali-state.sh and writes its
# contents into the right places in this repo. This is the step that used to be
# "spend an hour hand-editing group_vars" — it's mechanical, so it's scripted.
#
# Usage, from the repo root:
#
#   ./scripts/fold-capture.sh ~/kali-state-oldvm-20260811-1541
#   ./scripts/fold-capture.sh ~/kali-state-oldvm-20260811-1541 --dry-run
#
# What goes where:
#
#   15-packages.txt (or .ok.txt)  -> roles/apt_tools/files/packages.txt
#   20-pipx-names.txt             -> group_vars/all/zz-captured.yml : pipx_packages
#   25-go-tools.txt               -> group_vars/all/zz-captured.yml : go_packages
#   30-manual-tools.txt           -> group_vars/all/zz-captured.yml : opt_repos
#   40-dotfiles/                  -> roles/dotfiles/files/          (opt-in)
#   14-apt-sources.txt            -> REPORTED ONLY, needs a human
#
# Everything written is either a generated file (safe to overwrite) or backed
# up first. Your hand-written group_vars/all/main.yml is never touched.
#
set -euo pipefail

CAP="${1:-}"
DRY="${2:-}"

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
GEN="$REPO/group_vars/all/zz-captured.yml"
PKG="$REPO/roles/apt_tools/files/packages.txt"

log()  { printf '\033[1;32m[+]\033[0m %s\n' "$1"; }
warn() { printf '\033[1;33m[!]\033[0m %s\n' "$1"; }
err()  { printf '\033[1;31m[x]\033[0m %s\n' "$1" >&2; }
act()  { [[ "$DRY" == "--dry-run" ]] && printf '    would write: %s\n' "$1" || printf '    wrote: %s\n' "$1"; }

if [[ -z "$CAP" || ! -d "$CAP" ]]; then
  cat >&2 <<'EOF'
usage: ./scripts/fold-capture.sh <capture-dir> [--dry-run]

  capture-dir   the kali-state-<host>-<date>/ directory from capture-kali-state.sh
  --dry-run     show what would change, write nothing
EOF
  exit 1
fi

CAP="$(cd "$CAP" && pwd)"
log "Folding $CAP"
[[ "$DRY" == "--dry-run" ]] && warn "DRY RUN — nothing will be written"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# =============================================================================
# 1. APT packages -> roles/apt_tools/files/packages.txt
#
# Prefer the validated .ok.txt if validate-package-list.sh has been run, since
# it has already had retired names stripped. Fall back to the raw list.
# =============================================================================
SRC=""
for cand in "$CAP"/15-packages.ok.txt "$CAP"/*.ok.txt "$CAP"/15-packages.txt; do
  [[ -f "$cand" ]] && { SRC="$cand"; break; }
done

if [[ -n "$SRC" ]]; then
  COUNT=$(grep -Evc '^\s*(#|$)' "$SRC" || echo 0)
  log "APT packages: $COUNT from $(basename "$SRC")"
  if [[ "$(basename "$SRC")" == *.ok.txt ]]; then
    log "  (validated list — retired names already removed)"
  else
    warn "  Raw list — run validate-package-list.sh first if you haven't."
    warn "  The playbook filters retired names anyway, but you won't see the report."
  fi

  {
    echo "# kali-forge bulk package manifest"
    echo "# Generated by fold-capture.sh from $(basename "$CAP")"
    echo "# Source: $(basename "$SRC")"
    echo "#"
    echo "# Safe to edit by hand — re-running fold-capture.sh will overwrite it,"
    echo "# so commit your changes or keep additions in group_vars instead."
    echo
    grep -Ev '^\s*(#|$)' "$SRC" | sed -E 's/:[a-z0-9]+$//' | sort -u
  } > "$TMP/packages.txt"

  if [[ -f "$PKG" ]] && ! diff -q "$PKG" "$TMP/packages.txt" >/dev/null 2>&1; then
    ADDED=$(comm -13 <(grep -Ev '^\s*(#|$)' "$PKG" | sort -u) \
                     <(grep -Ev '^\s*(#|$)' "$TMP/packages.txt" | sort -u) | wc -l)
    REMOVED=$(comm -23 <(grep -Ev '^\s*(#|$)' "$PKG" | sort -u) \
                       <(grep -Ev '^\s*(#|$)' "$TMP/packages.txt" | sort -u) | wc -l)
    log "  change vs current manifest: +$ADDED / -$REMOVED"
  fi

  if [[ "$DRY" != "--dry-run" ]]; then
    [[ -f "$PKG" ]] && cp "$PKG" "$PKG.bak"
    cp "$TMP/packages.txt" "$PKG"
  fi
  act "$PKG"
else
  warn "No 15-packages.txt found — skipping the apt manifest."
fi

# =============================================================================
# 2. Build the generated group_vars file
# =============================================================================
{
  echo "---"
  echo "# ============================================================================="
  echo "# GENERATED FILE — DO NOT EDIT"
  echo "#"
  echo "# Written by scripts/fold-capture.sh from $(basename "$CAP")"
  echo "# Overwritten completely on every fold."
  echo "#"
  echo "# Loaded after main.yml (the zz- prefix sorts last), so anything defined"
  echo "# here overrides the placeholder defaults there."
  echo "#"
  echo "# To change these values permanently, either edit them in main.yml and"
  echo "# delete the corresponding block here, or fix them on the source VM and"
  echo "# re-capture."
  echo "# ============================================================================="
  echo
} > "$TMP/gen.yml"

# ---- pipx --------------------------------------------------------------------
if [[ -f "$CAP/20-pipx-names.txt" && -s "$CAP/20-pipx-names.txt" ]]; then
  N=$(grep -c . "$CAP/20-pipx-names.txt" || echo 0)
  log "pipx: $N package(s)"
  {
    echo "# --- pipx --------------------------------------------------------------------"
    echo "# Versions are pinned as captured. Drop the '==x.y.z' to track latest."
    echo "pipx_packages:"
    while read -r line; do
      [[ -z "$line" ]] && continue
      echo "  - $line"
    done < "$CAP/20-pipx-names.txt"
    echo
  } >> "$TMP/gen.yml"
else
  warn "No 20-pipx-names.txt — pipx_packages left to main.yml"
fi

# ---- go ----------------------------------------------------------------------
# Parse the "recovered module paths" table: <binary> <module-path> <mod@version>
if [[ -f "$CAP/25-go-tools.txt" ]]; then
  awk '
    /recovered module paths/ { inblock=1; next }
    inblock && NF>=2 && $2 != "?" && $2 ~ /\// { print $2 }
  ' "$CAP/25-go-tools.txt" | sort -u > "$TMP/go.txt" || true

  if [[ -s "$TMP/go.txt" ]]; then
    N=$(wc -l < "$TMP/go.txt")
    log "go: $N tool(s)"
    {
      echo "# --- go ----------------------------------------------------------------------"
      echo "# Module paths recovered from the binaries via 'go version -m'."
      echo "# @latest by default — pin a version if you need both machines identical."
      echo "go_packages:"
      while read -r p; do
        echo "  - $p@latest"
      done < "$TMP/go.txt"
      echo
    } >> "$TMP/gen.yml"
  else
    warn "No go module paths recovered — go_packages left to main.yml"
  fi
fi

# ---- /opt git repos ----------------------------------------------------------
if [[ -f "$CAP/30-manual-tools.txt" ]]; then
  awk '
    /^\/opt\// && /https?:\/\// {
      path=$1; url=$2;
      n=split(path, parts, "/"); name=parts[n];
      if (url != "<no" && name != "") print name "\t" url
    }
  ' "$CAP/30-manual-tools.txt" | sort -u > "$TMP/opt.txt" || true

  if [[ -s "$TMP/opt.txt" ]]; then
    N=$(wc -l < "$TMP/opt.txt")
    log "/opt repos: $N"
    {
      echo "# --- /opt git clones ---------------------------------------------------------"
      echo "# version: HEAD tracks the default branch. Pin to a commit SHA for any repo"
      echo "# you need byte-identical across both machines."
      echo "opt_repos:"
      while IFS=$'\t' read -r name url; do
        echo "  - name: $name"
        echo "    url: $url"
        echo "    version: HEAD"
      done < "$TMP/opt.txt"
      echo
    } >> "$TMP/gen.yml"
  else
    warn "No /opt git repos found — opt_repos left to main.yml"
  fi
fi

# ---- identity ----------------------------------------------------------------
if [[ -f "$CAP/00-system.txt" ]]; then
  # Both of these are best-effort. `|| true` matters: under `set -o pipefail`
  # a grep that matches nothing fails the whole pipeline and would abort the
  # script right at the end, after all the real work is done.
  OLDUSER=$(awk '/=== primary user ===/{getline; print}' "$CAP/00-system.txt" 2>/dev/null \
            | sed -E 's/.*uid=[0-9]+\(([^)]+)\).*/\1/' | head -1 || true)
  OLDTZ=$(grep -oP '(?<=Time zone: )[^ ]+' "$CAP/50-system-config.txt" 2>/dev/null | head -1 || true)
  if [[ -n "${OLDUSER:-}" && "$OLDUSER" != "root" ]]; then
    log "user: $OLDUSER"
    {
      echo "# --- identity ----------------------------------------------------------------"
      echo "forge_user: $OLDUSER"
      [[ -n "${OLDTZ:-}" ]] && echo "forge_timezone: $OLDTZ"
      echo
    } >> "$TMP/gen.yml"
  fi
fi

# Strip the trailing blank line each block leaves behind — yamllint's
# empty-lines rule rejects it, and `make lint` should stay green after a fold.
if [[ "$DRY" != "--dry-run" ]]; then
  awk 'NF {blank=0; print; next} {blank++; if (blank==1) print}' "$TMP/gen.yml" \
    | sed -E '${/^$/d}' > "$GEN"
fi
act "$GEN"

# =============================================================================
# 3. Dotfiles — opt-in, because these overwrite curated repo files
# =============================================================================
DOTSRC="$CAP/40-dotfiles"
if [[ -d "$DOTSRC" ]]; then
  echo
  log "Dotfiles captured at $DOTSRC:"
  find "$DOTSRC" -maxdepth 1 -type f -printf '      %f\n' 2>/dev/null | head -20
  warn "NOT copied automatically — roles/dotfiles/files/ holds curated versions"
  warn "  (forge.zsh, tmux.conf, init.lua) that the playbook manages."
  warn "  Copy individually if you want the old machine's instead:"
  warn "    cp $DOTSRC/zshrc $REPO/roles/dotfiles/files/"
fi

# =============================================================================
# 4. Third-party apt repos — the real gap, needs a human
# =============================================================================
if [[ -f "$CAP/14-apt-sources.txt" ]]; then
  THIRD=$(grep -E '^deb ' "$CAP/14-apt-sources.txt" 2>/dev/null \
          | grep -viE 'kali\.org|debian\.org' | sort -u || true)
  if [[ -n "$THIRD" ]]; then
    echo
    err "THIRD-PARTY APT REPOS FOUND — these are NOT handled automatically."
    echo "$THIRD" | sed 's/^/      /'
    echo
    warn "Packages that came from these will show as 'retired' on the new VM,"
    warn "because the new VM has no such repo configured. You need to add the"
    warn "repo and its signing key by hand before those packages resolve."
    warn "Full detail, including keyring paths: $CAP/14-apt-sources.txt"
  fi
fi

# =============================================================================
echo
log "Fold complete."
if [[ "$DRY" == "--dry-run" ]]; then
  log "Dry run — re-run without --dry-run to apply."
else
  cat <<EOF

  Review what changed:
    git -C "$REPO" diff --stat
    git -C "$REPO" diff group_vars/

  Then check the playbook agrees:
    cd "$REPO" && make check

EOF
fi
